import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect } from 'react'
import useSWR from 'swr'

export default function Home() {

  // useEffect( () => {
  //   const fetchdata = async () => {
  //     const response = await fetch('/api/people')
  //     const data = await response.json()
  //     console.log("data", data)
  //   }
  //   fetchdata()
  // }, [])

  // replace above fetch with SWR

  const { data, error } = useSWR('/api/people', (...args) => fetch(...args).then(res => res.json()))

  if(!data) {
    return <div>Loading...</div>
  } else {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App Class Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ul>
          {data.map(person => <li key={person.id}><Link href={`/person/${person.id}`}><a>{person.name}</a></Link></li>)}
        </ul>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
  }
}
